version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
      time: "05:00"
    open-pull-requests-limit: 99
    assignees:
      - sue445
    versioning-strategy: lockfile-only
