name: upgrade_terraform

on:
  push:
    paths:
      # common
      - "lib/base_runner.rb"
      - "Gemfile"
      - "Gemfile.lock"
      - ".ruby-version"

      - ".github/workflows/upgrade_terraform.yml"
      - "bin/upgrade_terraform"
      - "cookbooks/upgrade_terraform_version.rb"
      - "lib/terraform_update_runner.rb"

env:
  ASSIGNEE: sue445

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        include:
          # c.f. https://github.com/hashicorp/terraform/blob/main/CHANGELOG.md
          - repo: "sue445/terraform-aws-template"
            terraform_version: "1.3.2"

          - repo: "sue445/terraform-gcp-template"
            terraform_version: "1.3.2"

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          token:      ${{ steps.generate_token.outputs.token }}
          path:       tmp/repo/

      - run: ls -l tmp/repo/

      - name: Run ./bin/upgrade_terraform
        run: |
          set -xe

          git config --global user.email "version_updater@example.com"
          git config --global user.name "version_updater"

          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            export DRY_RUN=false
          else
            export DRY_RUN=true
          fi
          ./bin/upgrade_terraform
        env:
          GITHUB_TOKEN:      ${{ steps.generate_token.outputs.token }}
          GITHUB_REPO:       ${{ matrix.repo }}
          TERRAFORM_VERSION: ${{ matrix.terraform_version }}
          # LOG_LEVEL:         debug

      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: ${{ format('*upgrade_terraform* ({0})', matrix.repo) }}
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: lazy-actions/slatify@master
        if: always()
        continue-on-error: true
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
