name: upgrade_terraform

on:
  push:
    paths:
      # common
      - "lib/base_runner.rb"
      - "Gemfile"
      - "Gemfile.lock"
      - ".ruby-version"

      - ".github/workflows/upgrade_terraform.yml"
      - "bin/upgrade_terraform"
      - "cookbooks/upgrade_terraform_version.rb"
      - "lib/terraform_update_runner.rb"

env:
  ASSIGNEE: sue445

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        include:
          # c.f. https://github.com/hashicorp/terraform/blob/main/CHANGELOG.md
          - user: "sue445"
            repo: "terraform-aws-template"
            terraform_version: "1.13.3"

          - user: "sue445"
            repo: "terraform-gcp-template"
            terraform_version: "1.13.3"

    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key:  ${{ secrets.GH_PRIVATE_KEY }}
          owner:        ${{ matrix.user }}
          repositories: ${{ matrix.repo }}

      - name: checkout target repo
        uses: actions/checkout@v5
        with:
          repository: ${{ matrix.user }}/${{ matrix.repo }}
          token:      ${{ steps.generate_token.outputs.token }}
          path:       tmp/repo/

      - run: ls -l tmp/repo/

      - name: Run ./bin/upgrade_terraform
        run: |
          set -xe

          git config --global user.email "version_updater@example.com"
          git config --global user.name "version_updater"

          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            export DRY_RUN=false
          else
            export DRY_RUN=true
          fi
          ./bin/upgrade_terraform
        env:
          GITHUB_TOKEN:      ${{ steps.generate_token.outputs.token }}
          GITHUB_REPO:       ${{ matrix.repo }}
          TERRAFORM_VERSION: ${{ matrix.terraform_version }}
          # LOG_LEVEL:         debug

      - name: Slack Notification (not success)
        uses: act10ns/slack@v2
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          matrix: ${{ toJson(matrix) }}

  notify:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: act10ns/slack@v2
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
