name: upgrade_ruby

on:
  push:
    paths:
      # common
      - "lib/base_runner.rb"
      - "Gemfile"
      - "Gemfile.lock"
      - ".ruby-version"

      - ".github/workflows/upgrade_ruby.yml"
      - "bin/upgrade_ruby"
      - "cookbooks/upgrade_ruby_version.rb"
      - "lib/ruby_update_runner.rb"
      - "node.yml"

env:
  ASSIGNEE: sue445

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        include:
          - user: "sue445"
            repo: "myapp_version_upgrader"
            ruby_version: "3.4.2"

          # NOTE: Dependent on https://hub.docker.com/_/ruby
          - user: "sue445"
            repo: "dockerfile-packer-serverspec"
            ruby_version: "3.4"

          - user: "sue445"
            repo: "dockerhub-slack-webhook"
            ruby_version: "3.4"

          - user: "sue445"
            repo: "emoy_webhook"
            ruby_version: "3.4"

          - user: "sue445"
            repo: "rubicure-playground"
            ruby_version: "3.4"

          # NOTE: Dependent on https://hub.docker.com/r/cimg/ruby
          - user: "sue445"
            repo: "cure-mastodon-bots"
            ruby_version: "3.4"

          - user: "sue445"
            repo: "precure-birthday-calendar"
            ruby_version: "3.4"

          - user: "sue445"
            repo: "pretty-all-friends-birthday-calendar"
            ruby_version: "3.4"

          - user: "sue445"
            repo: "tweet_pixels"
            ruby_version: "3.4"

          # c.f. https://cloud.google.com/functions/docs/concepts/execution-environment#ruby
          - user: "sue445"
            repo: "pribirthdaybot"
            ruby_version: "3.3"

          - user: "sue445"
            repo: "regional-rb-calendar"
            ruby_version: "3.3"

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key:  ${{ secrets.GH_PRIVATE_KEY }}
          owner:        ${{ matrix.user }}
          repositories: ${{ matrix.repo }}

      - name: checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.user }}/${{ matrix.repo }}
          token:      ${{ steps.generate_token.outputs.token }}
          path:       tmp/repo/

      - run: ls -l tmp/repo/

      - name: Run ./bin/upgrade_ruby
        run: |
          set -xe

          git config --global user.email "version_updater@example.com"
          git config --global user.name "version_updater"

          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            export DRY_RUN=false
          else
            export DRY_RUN=true
          fi
          ./bin/upgrade_ruby
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GITHUB_REPO:  ${{ matrix.repo }}
          RUBY_VERSION: ${{ matrix.ruby_version }}
          # LOG_LEVEL:    debug

      - name: Slack Notification (not success)
        uses: act10ns/slack@v2
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          matrix: ${{ toJson(matrix) }}

  notify:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: act10ns/slack@v2
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
